baseurl = "https://alebaffa.com/"
title = "Welcome"
theme = "ghostwriter"
languageCode = "en-EN"
copyright = "(c) 2015 Alessandro Baffa."
googleAnalytics = "XXX"
disqusShortname = "alebaffa"
highlight = "monokai_sublime"

[Author]
    name = "Alessandro Baffa"
    profile = "https://twitter.com/alebaffa"

[Taxonomies]
    tag = "tags"

[Params]
    title = "blog"
    intro = true
    avatar = "speaker-small.jpg"
    headline = "アレバッファ - alebaffa"
    github = "https://github.com/alebaffa"
    linkedin = "https://linkedin.com/in/alessandrobaffa/"
    gplus = "https://google.com/+AlessandroBaffa"
    twitter = "https://twitter.com/alebaffa"
    # stackoverflow = "http://stackoverflow.com/users/XXX/YYY"
    powered_by = false

[Permalinks]
    post = "/:year/:month/:day/:title/"

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3