baseurl = "https://alebaffa.github.io/"
title = "alebaffa's"
theme = "ghostwriter"
languageCode = "en-EN"
copyright = "(c) 2015 Alessandro Baffa."
googleAnalytics = "XXX"
disqusShortname = "alebaffa"
highlight = "monokai_sublime"

[Author]
    name = "Alessandro Baffa"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "alebaffa.github.io"
    description = "Personal learning log"
    github = "https://github.com/alebaffa"
    linkedin = "https://linkedin.com/in/alessandrobaffa/"
    gplus = "https://google.com/+AlessandroBaffa"
    twitter = "https://twitter.com/alebaffa"
    # stackoverflow = "http://stackoverflow.com/users/XXX/YYY"

[Permalinks]
    post = "/:year/:month/:day/:title/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3