baseurl = "https://alebaffa.com/"
title = "Welcome"
theme = "ghostwriter"
copyright = "(c) 2015 Alessandro Baffa."
highlight = "monokai_sublime"

[Author]
    name = "Alessandro Baffa"
    profile = "https://twitter.com/alebaffa"

[Taxonomies]
    tag = "tags"

[Params]
    title = "blog"
    intro = true
    avatar = "speaker-small.jpg"
    headline = "~/alebaffa/weblog"
    github = "https://github.com/alebaffa"
    linkedin = "https://linkedin.com/in/alessandrobaffa/"
    gplus = "https://google.com/+AlessandroBaffa"
    twitter = "https://twitter.com/alebaffa"
    # stackoverflow = "http://stackoverflow.com/users/XXX/YYY"
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    powered_by = true
    dateFormat = "02-Jan-2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 3