baseurl = "https://www.alebaffa.com"
title = "Alessandro Baffa"

theme = "coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "alebaffa"

[params]
    author = "Alessandro Baffa"
    description = "Alessandro's personal website"
    keywords = "blog,developer,personal"
    info = "Computer Enginer"
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    hideCredits = false
    hideCopyright = false


    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    langseparator = "|"

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/alebaffa/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/alebaffa/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/alessandrobaffa/"
[[params.social]]
    name = "Medium"
    weight = 4
    url = "https://medium.com/alebaffa-blog"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"

[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Alessandro Baffa"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Alessandro Baffa"
        info = "Computer Engineer"
        description = "Alessandro's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2.0
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"