baseurl = "https://alebaffa.com/"
languageCode = "en-us"
title = "weblog"
theme = "hugo-classic"
googleAnalytics = "UA-114385313-1"
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"
disqusShortname = "alebaffa"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[author]
	Handle = "alebaffa"
	FirstName = "Alessandro"
	LastName = "Baffa"
	AboutPage = "/about"
	Location = "Tokyo, Japan"
    FlickrID = "50161185@N04"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[Params]
	Description = "Computer science is no more about computers than astronomy is about telescopes"
	ShowCopyright = true
	RSSEnabled = true
	RSSSections = [ "Posts", "Microposts", "Photos" ]
    RSSMicropostTitles = false
    dateFormat = "02/01/2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "About"
    url = "about"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    identifier = "projects"
    weight = 2

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    identifier = "categories"
    weight = 3

[[menu.feed]]
    name = "Subscribe"
    url = "/index.xml"