author = "Alessandro Baffa"
baseurl = "/"
canonifyurls = true
#copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 5
theme = "alageek"
title = "A Decentralized Blog"

[params]
copyright = "© 2020 by Alessandro Baffa"
copyrightUrl = "https://www.alebaffa.com"
description = "Alessandro Baffa website"
#faviconfile = "img/ale.jpg"
latestpostcount = 25
#logofile = "img/ale.jpg"
highlightjs = true
highlightjslanguages = [ "bash", "css", "diff", "java", "javascript", "python", "golang" ]
toc = true
posts_navigation = true
progressively = true
github = "alebaffa"
linkedin = "alessandrobaffa"
twitter = "alebaffa"
email = "contact@alebaffa.com"

#[[menu.primary]]
#identifier = "blog"
#name = "Blog"
#url = "/blog/"
#weight = 10

#[[menu.primary]]
#identifier = "about"
#name = "About"
#url = "/about/"
#weight = 20

#[[menu.secondary]]
#identifier = "patreon"
#name = "Become a patron"
#url = "https://www.patreon.com/bePatron?u=10637849"
#weight = 110

#[[menu.secondary]]
#identifier = "bmc"
#name = "Buy me a coffee"
#url = "https://www.buymeacoffee.com/gokmen"
#weight = 120

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 50
