author = "Alessandro Baffa"
baseurl = "/"
languageCode = "en-us"
canonifyurls = true
copyright = "Alessandro Baffa; some rights reserved."
paginate = 25
theme = "hugo-theme-cactus"
title = "alebaffa.eth"
relativeUrls = "true"

[params]
  colortheme = "dark" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  description = "Hi, I'm Alessandro Baffa, Software Engineer and Solutions Architect from Italy, now based in Tokyo. This is my personal blog, it lived multiple lives since 2007. My current interests are Cloud Computing, Blockchain and Web 3.0"
  mainSection = "blog" # your main section
  latestpostcount = 25
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 15 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  highlightjs = true
  highlightjslanguages = [ "bash", "css", "diff", "java", "javascript", "python", "golang" ]
  toc = true
  posts_navigation = true
  progressively = true
  github = "alebaffa"
  linkedin = "alessandrobaffa"
  twitter = "alebaffa"

[params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/alebaffa"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/alessandrobaffa/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/blog"
weight = 2

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

#[[menu.primary]]
#identifier = "blog"
#name = "Blog"
#url = "/blog/"
#weight = 10

#[[menu.primary]]
#identifier = "about"
#name = "About"
#url = "/about/"
#weight = 20

#[[menu.secondary]]
#identifier = "patreon"
#name = "Become a patron"
#url = "https://www.patreon.com/bePatron?u=10637849"
#weight = 110

#[[menu.secondary]]
#identifier = "bmc"
#name = "Buy me a coffee"
#url = "https://www.buymeacoffee.com/gokmen"
#weight = 120

[[menu.footer]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight =3
