baseurl = "https://alebaffa.com/"
title = "Welcome"
theme = "internet-weblog"
pygmentsstyle = "emacs"
SectionPagesMenu = "main"

[author]
	Handle = "alebaffa"
	FirstName = "Alessandro"
	LastName = "Baffa"
	AboutPage = "/about"
	Location = "Tokyo, Japan"
    FlickrID = "50161185@N04"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[Params]
	Description = "Computer science is no more about computers than astronomy is about telescopes"
	ShowCopyright = true
	RSSEnabled = true
	RSSSections = [ "Posts", "Microposts", "Photos" ]
    RSSMicropostTitles = false
    dateFormat = "02/01/2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    identifier = "posts"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    identifier = "projects"
    weight = 2

[[menu.main]]
    name = "Microposts"
    url = "/microposts/"
    identifier = "microposts"
    weight = 3